# Generated by Django 3.0.2 on 2020-01-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTwo',
        ),
    ]
